# Generated by Django 4.1.7 on 2023-05-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuscadorConciertos', '0004_alter_concierto_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierto',
            name='country',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
