# Generated by Django 4.0 on 2023-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuscadorConciertos', '0005_concierto_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_spotified',
            field=models.BooleanField(default=False),
        ),
    ]
